#!/usr/bin/env python3
"""Analyze structural diversity of selected frames across strategies.

For toy H2: H-H bond length distribution.
Compares uncertainty top-K vs uncertainty-diversity selection.
"""
import json, statistics, sys
from pathlib import Path

PROJ = Path("/data/zft/deepmd-al-hpc")
OUT = PROJ / "experiments" / "baselines" / "diversity_analysis.md"

# Selected frames from Round 0 for all strategies
SELECTIONS = {
    "uncertainty": PROJ / "experiments/baselines/uncertainty_topk_round000/selected_topk.json",
    "diversity": PROJ / "experiments/baselines/diversity_round000/selected_topk.json",
    "trust_level": PROJ / "experiments/baselines/trust_level_round000/selected_topk.json",
}

# We need coords to compute H-H distance. Use the NPZ from Round 0 prediction.
NPZ = PROJ / "experiments/exp_005_committee_prediction/committee_predictions.npz"


def hh_distance(coord):
    """H-H bond length from flattened coords [x1,y1,z1,x2,y2,z2]."""
    r1 = coord[:3]
    r2 = coord[3:6]
    return float(sum((a - b) ** 2 for a, b in zip(r1, r2)) ** 0.5)


def main():
    results = {}

    for name, json_path in SELECTIONS.items():
        if not json_path.exists():
            print(f"MISSING: {json_path}")
            continue

        sel = json.loads(json_path.read_text())
        indices = [f["frame_index"] for f in sel["selected_frames"]]
        fdm = [f["force_dev_max"] for f in sel["selected_frames"]]
        results[name] = {
            "indices": indices,
            "fdm": fdm,
            "n": len(indices),
            "fdm_mean": statistics.mean(fdm),
            "fdm_std": statistics.stdev(fdm) if len(fdm) > 1 else 0,
        }

        # Compute H-H distance if NPZ available
        if NPZ.exists():
            import numpy as np
            data = np.load(NPZ, allow_pickle=True)
            coords = data["coord"]
            dists = [hh_distance(coords[i]) for i in indices]
            results[name]["hh_dist_mean"] = statistics.mean(dists)
            results[name]["hh_dist_std"] = statistics.stdev(dists) if len(dists) > 1 else 0
            results[name]["hh_dist_min"] = min(dists)
            results[name]["hh_dist_max"] = max(dists)

            # Pairwise distance within selected set (diversity metric)
            pw_dists = []
            for i in range(len(indices)):
                for j in range(i + 1, len(indices)):
                    pw_dists.append(abs(dists[i] - dists[j]))
            results[name]["pw_dist_mean"] = statistics.mean(pw_dists) if pw_dists else 0
            results[name]["pw_dist_min"] = min(pw_dists) if pw_dists else 0
            results[name]["pw_dist_max"] = max(pw_dists) if pw_dists else 0

    # Generate Markdown
    lines = [
        "# Structural Diversity Analysis (Toy H2, Round 0 Selection)",
        "",
        "H-H bond length distribution of selected frames across strategies.",
        "",
        "## Selected Frames: Uncertainty vs Diversity",
        "",
        "| Strategy | N | H-H mean (A) | H-H std (A) | H-H range (A) | PW dist mean (A) | FDM mean |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]

    for name in ["uncertainty", "diversity", "trust_level"]:
        if name not in results:
            continue
        r = results[name]
        hh = f"{r.get('hh_dist_mean', 0):.4f}" if 'hh_dist_mean' in r else "NA"
        hh_s = f"{r.get('hh_dist_std', 0):.4f}" if 'hh_dist_std' in r else "NA"
        hh_r = f"{r.get('hh_dist_min', 0):.4f}-{r.get('hh_dist_max', 0):.4f}" if 'hh_dist_min' in r else "NA"
        pw = f"{r.get('pw_dist_mean', 0):.4f}" if 'pw_dist_mean' in r else "NA"

        lines.append(
            f"| {name} | {r['n']} | {hh} | {hh_s} | {hh_r} | {pw} | {r['fdm_mean']:.4f} |"
        )

    lines.extend([
        "",
        "## Interpretation",
        "",
        "- **Pairwise distance (PW dist)**: mean absolute difference in H-H bond length",
        "  between all pairs of selected frames. Higher = more diverse.",
        "- **Uncertainty top-K** selects highest force_dev_max frames, which may cluster",
        "  at similar bond lengths (low PW dist).",
        "- **Diversity (FPS)** spreads selections across the bond-length range,",
        "  giving higher PW dist at the cost of slightly lower average FDM.",
        "- **Trust-level** selects from the candidate region (intermediate uncertainty),",
        "  which may naturally cover a different bond-length range.",
        "",
        "## Limitations",
        "",
        "- Toy H2: only 1 degree of freedom (H-H distance). Real systems need richer descriptors.",
        "- Single round comparison; multi-round diversity evolution not yet analyzed.",
        "- Generated by `scripts/analysis/analyze_diversity.py`.",
    ])

    OUT.write_text("\n".join(lines))
    print(f"Wrote: {OUT}")
    for line in lines[:20]:
        print(line)


if __name__ == "__main__":
    main()
