#!/usr/bin/env python3
"""Check local data/toy_h2 directory inventory. Outputs Markdown table."""
from pathlib import Path
import sys

PROJ = Path("/data/zft/deepmd-al-hpc")
DATA = PROJ / "data" / "toy_h2"
OUT = PROJ / "experiments" / "local_data_inventory.md"

EXPECTED_DIRS = [
    "train", "valid",
    "round_001_train", "round_001_candidate",
    "round_002_train", "round_002_candidate",
    "round_003_train", "round_003_candidate",
]
for seed in ["seed0", "seed1", "seed2"]:
    for r in [1, 2, 3]:
        EXPECTED_DIRS.append(f"random_{seed}_round_{r:03d}_train")
        EXPECTED_DIRS.append(f"random_{seed}_round_{r:03d}_candidate")


def count_frames(data_dir: Path) -> str:
    """Return frame count or MISSING."""
    if not data_dir.exists():
        return "MISSING"
    set000 = data_dir / "set.000"
    coord = set000 / "coord.npy"
    if not coord.exists():
        return "NO_COORD"
    try:
        import numpy as np
        return str(np.load(coord).shape[0])
    except Exception:
        return "READ_ERROR"


def main() -> None:
    lines = [
        "# Local Data Inventory",
        "",
        f"Generated: 2026-05-25 | Host: shared-v100 | Path: {DATA}",
        "",
        "| Directory | Status | Frames |",
        "|---|---|---|",
    ]

    if not DATA.exists():
        lines.append("| (data/toy_h2) | MISSING | — |")
        OUT.write_text("\n".join(lines))
        print("data/toy_h2 not found — nothing to inventory.")
        return

    for d in sorted(EXPECTED_DIRS):
        dp = DATA / d
        if dp.exists():
            n = count_frames(dp)
            lines.append(f"| {d} | OK | {n} |")
        else:
            lines.append(f"| {d} | MISSING | — |")

    lines.extend([
        "",
        "## Notes",
        "",
        "- This inventory only lists directory existence and frame counts.",
        "- No `.npy` data files are committed to Git.",
        "- Generated by `scripts/analysis/check_local_data_inventory.py`.",
    ])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"Wrote: {OUT}")


if __name__ == "__main__":
    main()
