#!/usr/bin/env python3
"""Summarize four-strategy comparison results into CSV and Markdown.

Reads experiments/strategy_comparison_toy_h2/{strategy}/round_*/selected_topk.json
and any available metrics_summary.csv files.

Usage:
  python scripts/analysis/summarize_strategy_comparison.py
"""
from __future__ import annotations

import csv
import json
import statistics
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]
COMP_DIR = PROJECT_ROOT / "experiments" / "strategy_comparison_toy_h2"
STRATEGIES = ["random", "uncertainty", "uncertainty_diversity", "trust_level"]
ROUNDS = ["001", "002", "003"]


def fmt(v: Any) -> str:
    if v is None:
        return ""
    if isinstance(v, float):
        return f"{v:.6e}"
    return str(v)


def main() -> None:
    rows = []
    warnings = []

    for strategy in STRATEGIES:
        for rnd in ROUNDS:
            rd = COMP_DIR / strategy / f"round_{rnd}"
            sel_json = rd / "selected_topk.json"
            metrics_csv = rd / "metrics_summary.csv"

            row: dict[str, Any] = {
                "strategy": strategy,
                "round": rnd,
                "seed": "0",
                "train_frames": "",
                "candidate_frames": "",
                "selected_frames": "",
                "energy_rmse": "",
                "force_rmse": "",
                "selection_score_mean": "",
                "selection_score_max": "",
                "elapsed_train_seconds": "",
                "elapsed_predict_seconds": "",
            }

            if sel_json.exists():
                try:
                    d = json.loads(sel_json.read_text(encoding="utf-8"))
                    row["selected_frames"] = len(d.get("selected_indices", d.get("selected_frames", [])))
                    frames = d.get("selected_frames", [])
                    if frames:
                        scores = [f.get("force_dev_max", 0) for f in frames]
                        row["selection_score_mean"] = statistics.mean(scores)
                        row["selection_score_max"] = max(scores)
                except Exception as e:
                    warnings.append(f"{strategy}/round_{rnd}/selected_topk.json: {e}")

            if metrics_csv.exists():
                try:
                    with metrics_csv.open(encoding="utf-8") as f:
                        for line in csv.DictReader(f):
                            if line.get("model", "").strip().lower() == "mean":
                                row["energy_rmse"] = line.get("energy_rmse", "")
                                row["force_rmse"] = line.get("force_rmse", "")
                except Exception as e:
                    warnings.append(f"{strategy}/round_{rnd}/metrics_summary.csv: {e}")

            rows.append(row)

    # CSV
    csv_path = COMP_DIR / "strategy_summary.csv"
    fieldnames = list(rows[0].keys())
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            w.writerow({k: fmt(v) for k, v in r.items()})

    # Markdown
    md_lines = [
        "# Four-Strategy Comparison Summary",
        "",
        "## Results",
        "",
        "| Strategy | Round | Selected | E_RMSE | F_RMSE | Score Mean | Score Max |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for r in rows:
        md_lines.append(
            f"| {r['strategy']} | {r['round']} | {r['selected_frames']} | "
            f"{fmt(r['energy_rmse'])} | {fmt(r['force_rmse'])} | "
            f"{fmt(r['selection_score_mean'])} | {fmt(r['selection_score_max'])} |"
        )

    if warnings:
        md_lines.extend(["", "## Warnings", ""])
        for w in warnings:
            md_lines.append(f"- {w}")

    md_lines.extend([
        "",
        "## Notes",
        "",
        "- NA values indicate missing data files (run experiments first).",
        "- This is a toy H2 prototype comparison.",
        "- Generated by `scripts/analysis/summarize_strategy_comparison.py`.",
    ])

    md_path = COMP_DIR / "strategy_summary.md"
    md_path.write_text("\n".join(md_lines), encoding="utf-8")

    print(f"Wrote: {csv_path}")
    print(f"Wrote: {md_path}")
    if warnings:
        print(f"Warnings: {len(warnings)}")


if __name__ == "__main__":
    main()
