#!/usr/bin/env python3
"""Parse profile JSON files into CSV and Markdown summary.

Usage:
  python scripts/profiling/parse_profile_logs.py \
    --input-dir experiments/profiling/v100 \
    --output-csv experiments/profiling/v100/profile_summary.csv \
    --output-md experiments/profiling/v100/profile_summary.md
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]

FIELD_NAMES = [
    "stage", "elapsed_seconds", "exit_code", "hostname",
    "git_commit", "start_time", "end_time", "command",
]


def collect_records(input_dir: Path) -> list[dict[str, Any]]:
    records = []
    json_files = sorted(input_dir.glob("*.json"))
    if not json_files:
        return records
    for f in json_files:
        try:
            d = json.loads(f.read_text(encoding="utf-8"))
            records.append({k: d.get(k, "") for k in FIELD_NAMES})
        except Exception as e:
            print(f"Warning: skip {f.name}: {e}")
    return records


def fmt(v: Any) -> str:
    if v is None:
        return ""
    if isinstance(v, float):
        return f"{v:.1f}"
    return str(v)


def main() -> None:
    parser = argparse.ArgumentParser(description="Parse profile JSON files into CSV+MD.")
    parser.add_argument("--input-dir", required=True, help="Directory with profile JSON files.")
    parser.add_argument("--output-csv", required=True, help="Output CSV path.")
    parser.add_argument("--output-md", required=True, help="Output Markdown path.")
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    if not input_dir.exists():
        print(f"Input directory not found: {input_dir}")
        print("No profile JSON files to parse.")
        return

    records = collect_records(input_dir)

    if not records:
        print(f"No JSON files found in {input_dir}.")
        print("Run profile_command.py first to generate profile JSON files.")
        return

    # CSV
    csv_path = Path(args.output_csv)
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=FIELD_NAMES)
        w.writeheader()
        for r in records:
            w.writerow({k: fmt(v) for k, v in r.items()})

    # Markdown
    md_path = Path(args.output_md)
    md_lines = [
        "# Profile Summary",
        "",
        "| Stage | Elapsed (s) | Exit | Command |",
        "|---|---|---|---|",
    ]
    for r in records:
        cmd_short = r.get("command", "")[:80]
        md_lines.append(
            f"| {r['stage']} | {fmt(r['elapsed_seconds'])} | "
            f"{r['exit_code']} | {cmd_short} |"
        )

    total = sum(float(r.get("elapsed_seconds", 0) or 0) for r in records)
    failures = [r for r in records if r.get("exit_code", 0) != 0]
    md_lines.extend([
        "",
        f"**Total elapsed**: {total:.1f}s across {len(records)} stages.",
        f"**Failures**: {len(failures)} stage(s) with non-zero exit code.",
        "",
        "---",
        "*Generated by scripts/profiling/parse_profile_logs.py*",
    ])
    md_path.write_text("\n".join(md_lines), encoding="utf-8")

    print(f"Records: {len(records)}")
    print(f"Total elapsed: {total:.1f}s")
    print(f"Wrote CSV: {csv_path}")
    print(f"Wrote MD:  {md_path}")


if __name__ == "__main__":
    main()
